name: Build
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  build:
    container: debian:bookworm-slim
    runs-on: ubuntu-latest
    steps:
      - name: Set up dependencies
        run: |
          apt update
          apt install --assume-yes --no-install-recommends \
            libglib2.0-dev \
            meson
        env:
          DEBIAN_FRONTEND: noninteractive
      - name: Build
        run: |
          meson setup . build
          meson compile -C build
      - name: Upload build log
        uses: actions/upload-artifact@v3
        with:
          path: build/meson-logs/meson-log.txt
          retention-days: 7
